### PR TITLE
Add user reports

### PR DESCRIPTION
**Pull request by Zentro**
This adds 3 commands, 1 for the user to use:
`!report <uid> <message>`
`!reports`
`!viewreport <rid>`

How to test: Report another test account, see if the report is properly added. View the report and ensure the report message, IP, and reporter are all properly displayed.

### CODE REVIEW

**Comment by CuriousMike56** [comment]
Submitting report:
RoR_2024-09-15_13-41-00
WindowsTerminal_2024-09-15_13-41-09

No output from the `!reports` command on either client.

**Comment by ohlidalp** [comment]
I'm not at home this weekend, will review next week.

**Review by CuriousMike56 — APPROVED** [review]

**Comment by ohlidalp** [comment]
I noticed the `!report` command doesn't display the usage hint - you must type it `!report ` (followed by space) to get the usage hint, which I think is confusing considering this is for regular players rather than mods who read docs.

... funny enough, all commands are like this. For no good reason as far as I'm concerned. But let's tackle that in another PR.

**Review by ohlidalp — APPROVED** [review]
Tested on Windows 10 x64, works well.

**Pull request merged**
