### PR TITLE
🔧 Improve install logic

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Running the setup script now can be disabled with `PACKAGING=TRUE`
Also added packaging with cpack

### CODE REVIEW

**Comment by tritonas00** [comment]
I'm really against setup scripts on linux, in general. The proper method of installing anything is by using distro's package manager. In case of rorserver, we just clone, build and run the generated executable. There is no reason to install anything. I suggest completely remove the setup script.

**Comment by AnotherFoxGuy** [comment]
But the issue is that the setup script is needed for the `rorserver.service` to work correctly

**Comment by tritonas00** [comment]
Is there an uninstall script also?

**Comment by AnotherFoxGuy** [comment]
> Is there an uninstall script also?

No, but there never was one

**Review by tritonas00 — APPROVED** [review]

**Pull request merged**
