### PR TITLE
RoRnet 2.40 + Unicode/Windows improvements

### PR DESCRIPTION
**Pull request by only-a-ptr**
Internal multithreading improvements.

Windows: added proper handling of shutdown by closing console window (or pressing ctrl+break)

Introduced RoRnet 2.40: see the respective commit for details.

NOTE: Travis build is failing because of Webserver feature: it's been broken since I don't know when. Fixing in progress....

### CODE REVIEW

**Comment by Michael10055** [comment]
Since the RoRNet 2.40 changes were already merged into the rigs-of-rods repo, should this be merged as well? Mainly due to this: https://forum.rigsofrods.org/thread-1385-post-11109.html#pid11109

**Comment by only-a-ptr** [comment]
Uhh, I completely lost track with this, but I agree, it should be merged 👍

**Comment by Michael10055** [comment]
I don't have write permissions on this repo, so you'll have to do it 😆

**Comment by only-a-ptr** [comment]
I'll get to it soon.

**Pull request closed without merging**
