### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by Hiradur**
I just replaced the dependencies with newer files, other than that I didn't touch the code. It still compiles and apparently runs fine.

### CODE REVIEW

**Comment by Hiradur** [comment]
I should do this as well, if only it wouldn't be so annoying to set everything up under Windows...

**Comment by Max98** [comment]
I can try it out for windows if you need, just pm me.

**Comment by Hiradur** [comment]
That would be great, but I guess it won't work without defining __WIN32__ manually.

**Comment by Hiradur** [comment]
I added another commit that makes ror-server compile with very strict flags. It doesn't compile with these flags with Clang yet. I also removed most of the performance tuning flags. I believe they should be set by the user manually because they have different effects on different hardware.

**Comment by Hiradur** [comment]
Alright, I believe I found the answer to \_\_Win32\_\_ : 
According to this site: http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system

only \_WIN32 is compatible with all major compilers. I will fix it.

**Comment by Hiradur** [comment]
With all features turned on there are some problems with ctemplate so it shouldn't be merged right now.

**Comment by Hiradur** [comment]
I added another commit that fixes all remaining problems. Only the webserver can't be build but I realized that it doesn't build with upstream on Linux as well.

**Pull request merged**
