### PR TITLE
[WIP] Full scale refactor & integration with new serverlist

### PR DESCRIPTION
**Pull request by only-a-ptr**
All tabs -> spaces.
Removed STACKLOG.
Extracting utility code to Util.
Removing dead interfaces.
Continuous code cleanup.

EDIT: Ehh, whatever... I implemented the new serverlist integration here, too. It triggered further refactoring, anyway, so it fits pretty well.

### CODE REVIEW

**Comment by mikadou** [comment]
@only-a-ptr Did you look at this https://github.com/only-a-ptr/ror-server/pull/1 ?

**Comment by only-a-ptr** [comment]
@mikadou Didn't notice that... it seems it didn't trigger a notification.

Thanks for the fixes, but the branch you're presenting is a bit of a mess. Could you make another PR directly to https://github.com/RigsOfRods/ror-server with only your build-fixes? That way we know if it makes Travis happy and I can rebase atop it.

**Comment by mikadou** [comment]
@only-a-ptr Better solution: I created a new PR against your `full-scale-reformat` branch instead of `master`. https://github.com/only-a-ptr/ror-server/pull/2

**Comment by AnotherFoxGuy** [comment]
Have you tried building this with GUI?

**Comment by mikadou** [comment]
@AnotherFoxGuy Yes, as far as I can tell. These are the options used when built by Travis https://github.com/RigsOfRods/ror-server/blob/master/tools/travis/linux/build.sh#L3-L7

**Comment by mikadou** [comment]
@only-a-ptr Your JsonCpp vs Travis fixups seem to keep the gcc build failing.

**Comment by only-a-ptr** [comment]
@mikadou I cleaned it up.

**Comment by mikadou** [comment]
> Question: why this? 090b55d Why would Travis complain?

This defines the constant variables separately in every compilation unit which includes `http.h`. However, the constants are not always used in every single file that includes the header, resulting in:

    error: ‘Http::METHOD_DELETE’ defined but not used [-Werror=unused-variable]

I would also argue that it is cleaner to define these constant values in a single global place, than to have multiple identical but distinct definitions in each compilation unit.

**Comment by mikadou** [comment]
> Good ol' -Werror=overflow nag. Any suggestions?

Looks like this change you made is missing https://github.com/RigsOfRods/ror-server/commit/003a32db474016632e98b9855af4682403429b5e

**Comment by only-a-ptr** [comment]
@mikadou 
> I would also argue that it is cleaner to define these constant values in a single global place, than to have multiple identical but distinct definitions in each compilation unit.
Yes. That's actually what I wanted to archieve, except I got it wrong :blush: 

> Looks like this change you made is missing 003a32d

2 things:
- how did you make a link to a commit that I threw away during `rebase` and `push --force`?
- I don't really know why I threw it away, I vaguely remember it was unhelpful or conflicted with sthg. else, even though it doesn't really make sense. Did you try it in your repo? Did it help?

**Comment by only-a-ptr** [comment]
I merged it now so that it no longer blocks joint development.
Pull requests to fix Travis are welcome.

**Pull request merged**
